### ISSUE TITLE
Doesn't show valid attribute

### ISSUE THREAD

**Issue by LucasDaiki** [scup/speck#2]
The errors object should has a valid attribute.
Eg.:
```
  static SCHEMA = {
    title: titleValidator
  }


function titleValidator(obj, field) {
  if (!obj[field]) {
    return new Error("Title can't be empty");
  }
}
```
Response
`Entity = { 
 "errors":{
   "title":{
     "errors":["Title can't be empty"]
   },
 "valid":false
}`

Expected
`Entity =  { 
 "errors":{
   "title":{
     "errors":["Title can't be empty"],
     "valid":false
   },
 "valid":false
}`

**Comment by guisouza** [comment]
```javascript
Entity.title.valid === !Entity.errors.hasOwnProperty('title')
```
I think is unnecessary for now.
