### ISSUE TITLE
Weird behaviour on toJSON method

### ISSUE THREAD

**Issue by danielbdias** [scup/speck#24]
When you fill a child element with an invalid value toJSON method acts in a weird way. The parent `toJSON` returns the old child element and the `toJSON` of the child element returns the child element in the invalid state.

For example, given the schema:

```javascript
class MyEntity extends Speck {
  static SCHEMA = {
    field: PropTypes.string,
    anotherField: PropTypes.string
  }
}

class FatherEntity extends Speck {
  static SCHEMA = {
    child: PropTypes.instanceOf(MyEntity)
  }
}
```

And the variables setup:

```javascript
const a = new FatherEntity({ child: { field: 'value' } })
a.child = { field: 'invalid entity', anotherField: 'yet a invalid entity' }
```

The `toJSON` method have this behaviour:

```javascript
//prints { child: { field: 'value' } }
console.log(a.toJSON()) 
//prints { field: 'invalid entity', anotherField: 'yet a invalid entity' }
console.log(a.child.toJSON()) 
```

**Comment by guisouza** [comment]
try with : 
```
class FatherEntity extends Speck {
  static SCHEMA = {
    child: {
      validator: PropTypes.instanceOf(MyEntity),
      type: MyEntity
    }
  }
}
```

**Comment by guisouza** [comment]
@danielbdias should we close this issue ?

**Comment by danielbdias** [comment]
Please, @guisouza not yet, can you wait two more days? I will do one more test to simulate this error (and another to use your solution). 
Thanks !

**Comment by guisouza** [comment]
No problem, take your time ..

**Comment by danielbdias** [comment]
I can't simulate this error anymore. For now I think that is better to close this issue.
